In [ ]:
#IMPORT PANDAS LIBRARY
import pandas as pd
#READ THE COSTS CSV
costs_df=pd.read_csv(r"D:\VS_CODE\Logistics\costs.csv")
costs_df.head()

  shipment_id  fuel_cost  labor_cost  misc_cost
0    dc84cc15      61.08       27.24      20.75
1    ca536e73      13.74       65.13      17.63
2    704fa19e      72.68       39.47      16.84
3    aad8a598      53.69       23.23      33.16
4    e120d4ba      90.24      107.29      14.73

In [ ]:
#READ THE COURIER STAFF CSV
courier_staff_df=pd.read_csv(r"D:\VS_CODE\Logistics\courier_staff.csv")
print(courier_staff_df.head())

  courier_id           name  rating vehicle_type
0   7bc57152   Justin Flynn     4.8          Van
1   87cafee3  Sherry Conrad     3.2        Truck
2   53cc593b     Joanna Liu     4.0          Car
3   c482832b   Samantha Lee     4.9          Car
4   a217d894  Carrie Santos     3.9          Van

In [ ]:
#READ THE ROUTES CSV
routes_df=pd.read_csv(r"D:\VS_CODE\Logistics\routes.csv")
routes_df.head()

   route_id         origin     destination  distance_km  avg_time_hours
0  fe423f38  East Victoria   South Raymond      1016.50            44.2
1  080ff620     Mooreshire      Davidshire        58.30            45.3
2  aa6e4a5f     Mooreshire   South Raymond       977.98            42.4
3  3aa7af93        Kimfort  East Johnshire       691.84            35.7
4  39913248     Tiffanyton      East David      1836.43            24.4

In [6]:
import sys
print("Python executable:", sys.executable)

Python executable: d:\VS_CODE\Logistics\venv\Scripts\python.exe

In [ ]:
import pandas as pd
#READ THE SHIPMENT TRACKING CSV
shipment_tracking_df = pd.read_excel(
    r"D:\VS_CODE\Logistics\shipment_tracking.xlsx",
    engine="openpyxl"
)
print(shipment_tracking_df.head())

   tracking_id shipment_id        status           timestamp
0            1    dc84cc15  Order Placed 2025-06-12 02:00:00
1            2    dc84cc15     Cancelled 2025-06-15 00:00:00
2            3    ca536e73  Order Placed 2025-06-27 02:00:00
3            4    ca536e73     Cancelled 2025-06-28 00:00:00
4            5    704fa19e  Order Placed 2025-09-09 03:00:00

In [ ]:
#READ THE SHIPMENTS CSV
shipments_df=pd.read_json(r"D:\VS_CODE\Logistics\shipments.json")
shipments_df.head()

,shipment_id,order_date,origin,destination,weight,courier_id,status,delivery_date
0,dc84cc15,2025-06-12,North Dawnfort,Ginafort,43.52,b554e6a4,Cancelled,None
1,ca536e73,2025-06-27,North Williamchester,Christinechester,19.31,9b44d9ca,Cancelled,None
2,704fa19e,2025-09-09,New Colleen,West Jared,27.97,f8c3e908,Delivered,2025-09-13
3,aad8a598,2025-07-25,South Ashleystad,Jonestown,18.74,0de3fc1b,Cancelled,None
4,e120d4ba,2026-01-06,Darinton,West Jared,39.30,44def2f4,In Transit,None

In [ ]:
#READ THE WAREHOUSES CSV
warehouses_df=pd.read_json(r"D:\VS_CODE\Logistics\warehouses.json")
warehouses_df.head()

  warehouse_id                  city state  capacity
0     647a65d8     North Claudiatown    SC      9821
1     8bdbd012            East David    MT      1138
2     cfcbd086          North Justin    ND      6019
3     3bff4497    Port Sandrachester    CT      3300
4     6767e7a4  North Williamchester    SD      6822

In [ ]:
#CONNECT TO THE SQL SERVER
import mysql.connector
from mysql.connector import Error,connect
def create_connection():
  connection=connect(
    host="localhost",
    user="root",
    password="root",
    database="logistics"
  )
  try:
   if connection.is_connected():
    print("Successfully connected to the database")
    return connection
  except Error as err:
    print(f"Error: {err}")
    return None



create_connection()

Successfully connected to the database

In [ ]:
#WRITE THE CSV FILES TO THE SQL TABLES IN MYSQL SERVER
import pandas as pd
from sqlalchemy import create_engine

#  MySQL connection string
engine = create_engine("mysql+mysqlconnector://root:root@localhost/logistics")

# Write the DataFrame cost_df to SQL
costs_df.to_sql(
    name="costs",        # table name
    con=engine,          # connection/engine
    schema="logistics",  # schema (optional, depends on DB)
    if_exists="replace", 
    index=False          # don’t write DataFrame index as a column
)

70000

In [ ]:

# Write the DataFrame courier_staff_df to SQL
courier_staff_df.to_sql(
    name="courier_staff",        # table name
    con=engine,          # connection/engine
      
    if_exists="replace", 
    index=False          # don’t write DataFrame index as a column
)

1000

In [17]:
 #Write the DataFrame routes_df to SQL
routes_df.to_sql(
    name="routes",        # table name
    con=engine,          # connection/engine
      
    if_exists="replace", 
    index=False          # don’t write DataFrame index as a column
)

500

In [18]:
#Write the DataFrame shipment_tracking_df to SQL
shipment_tracking_df.to_sql(
    name="shipment_tracking",        # table name
    con=engine,          # connection/engine
      
    if_exists="replace", 
    index=False          # don’t write DataFrame index as a column
)

209570

In [19]:
#Write the DataFrame shipments_df to SQL
shipments_df.to_sql(
    name="shipments",        # table name
    con=engine,          # connection/engine
      
    if_exists="replace", 
    index=False          # don’t write DataFrame index as a column
)

70000

In [20]:
#Write the DataFrame warehouses_df to SQL
warehouses_df.to_sql(
    name="warehouses",        # table name
    con=engine,          # connection/engine
      
    if_exists="replace", 
    index=False          # don’t write DataFrame index as a column
)

50